[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'nodePackages.typescript']

[phases.install]
cmds = ['yarn install --frozen-lockfile', 'yarn add typescript']

[phases.build]
cmds = ['yarn build']

[start]
cmd = 'yarn start'
