export enum MovieReferenceSortType {
  GENRE = 'GENRE',
  DECADE = 'DECADE',
  YEAR = 'YEAR',
  // SERVICE = 'SERVICE',
  // POPULARITY_YEAR = 'POPULARITY_YEAR',
  // POPULARITY_ASC = 'POPULARITY_ASC',
  // POPULARITY_DESC = 'POPULARITY_DESC',
  RELEASE_RECENT = 'RELEASE_DATE_RECENT',
  RELEASE_OLDER = 'RELEASE_DATE_OLDER',
}
