[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'nodePackages.typescript', 'nodePackages.ts-node']

[phases.install]
cmds = ['yarn install --frozen-lockfile']

[phases.build]
cmds = ['yarn build', 'yarn production:migrate']

[start]
cmd = 'yarn start'
