[phases.setup]
nixPkgs = ['nodejs', 'yarn', 'nodePackages.typescript', 'nodePackages.ts-node']

[phases.install]
cmds = ['yarn install --frozen-lockfile', 'yarn add typescript']

[phases.build]
cmds = ['yarn build', 'yarn migration:run']

[start]
cmd = 'yarn start'
